engines:
  rubocop:
    enabled: true
    channel: rubocop-0-52
    config:
      file: .rubocop.yml
  bundler-audit:
    enabled: true
ratings:
  paths:
    - lib/lsolr.rb
exclude_paths:
  - test/test_lsolr.rb
  - .bundle/**/*
