---
# https://rubocop.readthedocs.io/en/latest/
AllCops:
  TargetRubyVersion: 2.4
  DisplayCopNames: true

Metrics/AbcSize:
  Exclude:
    - 'test/**/*'

Metrics/ClassLength:
  Max: 400

Metrics/MethodLength:
  Exclude:
    - 'test/**/*'

Metrics/LineLength:
  Max: 200

Style/NumericPredicate:
  Enabled: false

Style/FormatStringToken:
  Enabled: false

Gemspec/RequiredRubyVersion:
  Enabled: false
