---
language: "ruby"
sudo: false
notifications:
  email: false
rvm:
  - "2.2.2"
  - "2.3.3"
  - "2.4.2"
before_install:
  - "gem update --system"
  - "gem install bundler"
  - "gem install rubocop"
script:
  - "bundle install --path=.bundle"
  - "ruby -w -I test -I lib test/lsolr_test.rb"
  - "rubocop --fail-level=W ."
