---
name: Test
on:
  push:
    branches:
      - "*"
  pull_request:
    branches:
      - "*"
jobs:
  lint:
    name: Lint
    timeout-minutes: 5
    strategy:
      matrix:
        os: ["ubuntu-latest"]
        ruby: ["3.1"]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: Lint
        run: bundle exec rubocop
  main:
    name: Main
    timeout-minutes: 5
    strategy:
      matrix:
        os: ["ubuntu-latest"]
        ruby: ["2.7", "3.0", "3.1"]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: Test
        run: bundle exec rake test
  sub:
    name: Sub
    timeout-minutes: 5
    strategy:
      matrix:
        os: ["ubuntu-latest"]
        ruby: ["2.5", "2.6"]
    runs-on: ${{ matrix.os }}
    steps:
      - name: Check out code
        uses: actions/checkout@v3
      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true
      - name: Test
        run: bundle exec rake test
